### ISSUE TITLE
Issue inferring types for ArrayCollection::filter

### ISSUE THREAD

**Issue by Alexander882** [weirdan/doctrine-psalm-plugin#13] opened 2019-04-04 11:50 UTC
Hi again. Sorry for the spamming 😅

Using the below snippet, I get the following error `InvalidTemplateParam - ... - Extended template param TKey expects type array-key, type empty given`.

```php
<?php
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
class Test
{
    /**
     * @var Collection<int, string>
     */
    private $strings;

    public function __construct()
    {
        $this->strings = new ArrayCollection();

        $this->strings->filter(
            function (string $s):bool {
                return $s !== '';
            });
    }
}
```

The same error comes when using `strings->map`, but not when using `strings->exists` or `strings->forAll`.
I can also prevent the error by adding a type annotation to the property initialization like this:

```php
/** @var Collection<int, string> strings */
$this->strings = new ArrayCollection();
```

Any ideas what might be causing this issue?

**Comment by weirdan** [comment] 2019-04-04 12:19
Psalm remembers types assigned to object properties during the method analysis. So here it effectively (temporarily) replaces the `$this->string` type with whatever the type of the right-hand-side of the assignment had (namely `ArrayCollection<empty,empty>`, since it was instantiated with `array<empty,empty>`), leading to this error.

Working this around involves making sure the type of the assigned value is what you expect it to be, either accepting it from outside, providing the typed array as a constructor parameter or (what you discovered yourself) using the assignment expression docblocks (they don't have to include the var name):
```php
/** @var ArrayCollection<int, string> */
$this->strings = new ArrayCollection();
```

I was kinda expecting to see InvalidPropertyAssignment popping up there though. Gotta experiment with that and, possibly, file a bug on Psalm's own issue tracker.

**Comment by weirdan** [comment] 2019-04-04 13:11
> I was kinda expecting to see InvalidPropertyAssignment popping up there

Well, `empty` appears to be a bottom type, thus being a subtype of any type, so it's not a bug.

**Comment by Alexander882** [comment] 2019-04-05 10:12
Allright I guess that makes sense. Thank you again very much for the help!

**Closed** 2019-04-05 10:12 UTC
